spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test_db
    username: root
    password: root
    hikari:
      minimum-idle: 20
      maximum-pool-size: 20
      max-lifetime: 21600000
      connection-timeout: 10000
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    open-in-view: false
  sql:
    init:
      mode: always
